---
- name: playbook_1
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  
  tasks: 
  - name: install_apache
    yum: 
      name: httpd
      state: latest
  
  - name: enable_httpd.service
    ansible.builtin.service:
      name: httpd
      state: started
  
  - shell: systemctl status httpd
    register: results

  - debug:
      var: results


  - name: create file /var/www/html/index.html with content
    copy: 
      dest: "/var/www/html/index.html"
      content: |
        Welcome to my web server 

  - name: open ports
    firewalld:
      port: 80/tcp
      immediate: yes
      permanent: yes
      state: enabled

  - name: open ports
    firewalld:
      port: 22/tcp        
      immediate: yes
      permanent: yes
      state: enabled

  - name: open ports
    firewalld:
      port: 111/tcp        
      immediate: yes
      permanent: yes
      state: enabled

