---
- name: "playbook_for_Kernel"
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  
  tasks:   
  - name: Change line in /etc/default/grub. 
    lineinfile:
      path: /etc/default/grub   
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=0 biosdevname=0)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0 biosdevname=0\2'
  - name: "Command run for apply grub changes"
    shell: grub2-mkconfig
    register: results
 
  - debug: 
      var: results 
      
